---
title: "Projection Plots"
author: "Air Singh"
date: "2023-06-04"
output: pdf_document
---

```{r setup, include=FALSE}
# setup
knitr::opts_chunk$set(echo = FALSE, results = "hide")
setwd('/Users/ankitasingh/Documents/STA-160-Final/')
library(ggplot2)
library(RColorBrewer)

```



```{r}
df_aqua= read.csv("Aqua-Data.csv")
```

For the aqua Marylin image,

```{r}
ggplot(df_aqua, aes(x=R, y=G, color = B )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  geom_abline(slope = .5,intercept = 100, linetype = 2)+
  scale_y_continuous(breaks=seq(0,255,25)) +
  scale_color_gradient(low = "#3DFAF4", high = "#318381")
```





```{r}
ggplot(df_aqua, aes(x=R, y=B, color = G )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#3DFAF4", high = "#318381")
```



```{r}
ggplot(df_aqua, aes(x=G, y=B, color = R)) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25)) +
  scale_color_gradient(low = "#3DFAF4", high = "#318381")
```





```{r}
df_green= read.csv("Green-Data.csv")
```



```{r}
ggplot(df_green, aes(x=R, y=G, color = B )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0FF808", high = "#276825")
```




```{r}
ggplot(df_green, aes(x=R, y=B, color = G )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0FF808", high = "#276825")
```



```{r}
ggplot(df_green, aes(x=G, y=B, color = R )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0FF808", high = "#276825")
```

```{r}
df_blue= read.csv("Blue-Data.csv")
```

```{r}
ggplot(df_blue, aes(x=R, y=G, color = B )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0285F9", high = "#254368")
```

```{r}
ggplot(df_blue, aes(x=R, y=B, color = G )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0285F9", high = "#254368")
```


```{r}
ggplot(df_blue, aes(x=G, y=B, color = R )) +
  geom_point() + scale_x_continuous(breaks=seq(0,255,25)) +
  scale_y_continuous(breaks=seq(0,255,25))  +
  scale_color_gradient(low = "#0285F9", high = "#254368")
```

















